name: Android

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Preprare tools
        run: sudo apt update && sudo apt install docker docker.io -y

      # Runs a set of commands using the runners shell
      - name: Run Preparing tool
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          tailscale up
      
      - name: Start
      run: |
        apt install linux-modules-extra-`uname -r`
        modprobe binder_linux devices="binder,hwbinder,vndbinder"
        modprobe ashmem_linux
        docker run -itd --rm --privileged \
        --pull always \
        -v ~/data:/data \
        -p 5555:5555 \
        --name redroid12 \
        --cpus "3.0"
        redroid/redroid:12.0.0-latest
       - name: Starting
       run: |
         timeout 3600
         timeout 3600
         timeout 3600
         timeout 3600
